base: &base
  database:
    host: 128.110.25.99
    port: 5432
    database: accountdb

  observer:
    base_path: ./signals
    sf31_orders_dir: sf31_orders
    xq_signals_dir: xq_signals
    order_callback_dir: order_callback
    order_callback_file: Order.txt
    trade_callback_file: Deal.txt
    position_callback_file: Position.txt

  engine:
    signal_start_time: "0820"
    signal_end_time: "1430"
    before_market_start_time: "0830"
    before_market_end_time: "0900"
    trade_start_time: "0840"
    trade_end_time: "1430"
    sync_start_time: "0750"
    sync_end_time: "1500"
    update_contracts_time: "0815"
    reset_time1: "0750"
    reset_time2: "1500"

  exit_handler:
    quote_delay_tolerance: 120

  order_manager:
    daily_amount_limit: 10000000
  
  loguru:
    sink_dir: ./log
    sink_file: bunny_order.log
    level: DEBUG

  common:
    checkpoints_dir: ./checkpoints


local: &local
  <<: *base


prod: &prod
  <<: *base
  observer:
    base_path: /opt/signals
    sf31_orders_dir: print
    xq_signals_dir: XQ_output
    order_callback_dir: status
    order_callback_file: Order.txt
    trade_callback_file: Deal.txt
    position_callback_file: Position.txt

  loguru:
    sink_dir: ./log
    sink_file: bunny_order.log
    level: INFO