FROM continuumio/miniconda3:4.11.0

RUN apt-get update && apt-get install -y vim

RUN pip config --user set global.index-url http://sinopypi.sec/simple/ && \
    pip config --user set global.trusted-host sinopypi.sec
ADD requirements.txt /opt/requirements.txt
RUN pip install -r /opt/requirements.txt